
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wiatrnfvzuqcmcfdnbuw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndpYXRybmZ2enVxY21jZmRuYnV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5NzYyMDgsImV4cCI6MjA3MDU1MjIwOH0.VKHOiglGclTKC-cuCWNzOP86nV9V1t0b7ssBYDeEoXI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
